# RDS DB Subnet groups
---

Resources:

  DBSubnetPrivate:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription:
        Fn::Join:
          - ""
          -
            - Private (
            - Ref: VPCName
            - )
      SubnetIds:
        - Ref: SubnetPrivateAZ1
        - Ref: SubnetPrivateAZ2
        - Ref: SubnetPrivateAZ3

  DBSubnetPublic:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription:
        Fn::Join:
          - ""
          -
            - Public (
            - Ref: VPCName
            - )
      SubnetIds:
        - Ref: SubnetPublicAZ1
        - Ref: SubnetPublicAZ2
        - Ref: SubnetPublicAZ3
