# Subnet declarations
#
# Please keep in CIDR order
#
# x.x.0.0/18 - AZ 1
#   x.x.0.0/20 - Private subnet
#   x.x.16.0/21 - Public subnet
#   x.x.24.0/21 - Spare
#   x.x.32.0/19 - Spare
# x.x.64.0/18 - AZ 2
#   x.x.64.0/20 - Private subnet
#   x.x.80.0/21 - Public subnet
#   x.x.88.0/21 - Spare
#   x.x.96.0/19 - Spare
# x.x.128.0/18 - AZ 3
#   x.x.128.0/20 - Private subnet
#   x.x.144.0/21 - Public subnet
#   x.x.152.0/21 - Spare
#   x.x.160.0/19 - Spare
# x.x.192.0/18 - Spare
---

Resources:

##
# Begin Subnet Private AZ 1 {
##

  SubnetPrivateAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Join:
          - ""
          -
            - Ref: AWS::Region
            - Fn::Select:
                - 0
                - Ref: AvailabilityZones
      CidrBlock:
        Fn::Join:
          - .
          -
            - Ref: VPCSupernetPrefix
            - 0.0/20
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - ""
              -
                - 'Private AZ '
                - Fn::Select:
                    - 0
                    - Ref: AvailabilityZones
                - ', uses NAT ('
                - Ref: VPCName
                - )
      VpcId:
        Ref: VPC

  AssociateSubnetPrivateAZ1RouteTableNATAZ1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTableNATAZ1
      SubnetId:
        Ref: SubnetPrivateAZ1

##
# End Subnet Private AZ 1 }
##

##
# Begin Subnet Public AZ 1 {
##

  SubnetPublicAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Join:
          - ""
          -
            - Ref: AWS::Region
            - Fn::Select:
                - 0
                - Ref: AvailabilityZones
      CidrBlock:
        Fn::Join:
          - .
          -
            - Ref: VPCSupernetPrefix
            - 16.0/21
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - ""
              -
                - 'Public AZ '
                - Fn::Select:
                    - 0
                    - Ref: AvailabilityZones
                - ', requires EIP ('
                - Ref: VPCName
                - )
      VpcId:
        Ref: VPC

  AssociateSubnetPublicAZ1RouteTableInternetGateway:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTableInternetGateway
      SubnetId:
        Ref: SubnetPublicAZ1

##
# End Subnet Public AZ 1 }
##

##
# Begin Subnet Private AZ 2 {
##

  SubnetPrivateAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Join:
          - ""
          -
            - Ref: AWS::Region
            - Fn::Select:
                - 1
                - Ref: AvailabilityZones
      CidrBlock:
        Fn::Join:
          - .
          -
            - Ref: VPCSupernetPrefix
            - 64.0/20
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - ""
              -
                - 'Private AZ '
                - Fn::Select:
                    - 1
                    - Ref: AvailabilityZones
                - ', uses NAT ('
                - Ref: VPCName
                - )
      VpcId:
        Ref: VPC

  AssociateSubnetPrivateAZ2RouteTableNATAZ2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTableNATAZ2
      SubnetId:
        Ref: SubnetPrivateAZ2

##
# End Subnet Private AZ 2 }
##

##
# Begin Subnet Public AZ 2 {
##

  SubnetPublicAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Join:
          - ""
          -
            - Ref: AWS::Region
            - Fn::Select:
                - 1
                - Ref: AvailabilityZones
      CidrBlock:
        Fn::Join:
          - .
          -
            - Ref: VPCSupernetPrefix
            - 80.0/21
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - ""
              -
                - 'Public AZ '
                - Fn::Select:
                    - 1
                    - Ref: AvailabilityZones
                - ', requires EIP ('
                - Ref: VPCName
                - )
      VpcId:
        Ref: VPC

  AssociateSubnetPublicAZ2RouteTableInternetGateway:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTableInternetGateway
      SubnetId:
        Ref: SubnetPublicAZ2

##
# End Subnet Public AZ 2 }
##

##
# Begin Subnet Private AZ 3 {
##

  SubnetPrivateAZ3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Join:
          - ""
          -
            - Ref: AWS::Region
            - Fn::Select:
                - 2
                - Ref: AvailabilityZones
      CidrBlock:
        Fn::Join:
          - .
          -
            - Ref: VPCSupernetPrefix
            - 128.0/20
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - ""
              -
                - 'Private AZ '
                - Fn::Select:
                    - 2
                    - Ref: AvailabilityZones
                - ', uses NAT ('
                - Ref: VPCName
                - )
      VpcId:
        Ref: VPC

  AssociateSubnetPrivateAZ3RouteTableNATAZ3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTableNATAZ3
      SubnetId:
        Ref: SubnetPrivateAZ3

##
# End Subnet Private AZ 3 }
##

##
# Begin Subnet Public AZ 3 {
##

  SubnetPublicAZ3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Join:
          - ""
          -
            - Ref: AWS::Region
            - Fn::Select:
                - 2
                - Ref: AvailabilityZones
      CidrBlock:
        Fn::Join:
          - .
          -
            - Ref: VPCSupernetPrefix
            - 144.0/21
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - ""
              -
                - 'Public AZ '
                - Fn::Select:
                    - 2
                    - Ref: AvailabilityZones
                - ', requires EIP ('
                - Ref: VPCName
                - )
      VpcId:
        Ref: VPC

  AssociateSubnetPublicAZ3RouteTableInternetGateway:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTableInternetGateway
      SubnetId:
        Ref: SubnetPublicAZ3

##
# End Subnet Public AZ 3 }
##
