# Setup the VPC and top-level requirements
---

Description: VPC spanning 3 AZs with large subnets

Parameters:
  VPCName:
    Default: VPC
    Description: The name of this VPC
    MinLength: 1
    Type: String
  VPCSupernetPrefix:
    AllowedPattern: '^(?:[1-9]?[0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.(?:[1-9]?[0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$'
    ConstraintDescription: must only contain the first 2 octets
    Default: '10.11'
    Description: First 2 octets of the VPC CIDR supernet
    Type: String
  AvailabilityZones:
    Default: 'a,b,c'
    Description: The availability zones this VPC should span. Only the first 3 will be used
    Type: CommaDelimitedList
  CorpSubnet1:
    AllowedPattern: '^(?:(?:[1-9]?[0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}(?:[1-9]?[0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])/(?:[12]?[0-9]|3[0-2])$'
    ConstraintDescription: must be in CIDR notation (e.g., 192.168.0.0/24)
    Default: '192.168.10.0/24'
    Description: The subnet of the corporate LAN
    Type: String
  EnableDnsHostnames:
    AllowedValues:
      - false
      - true
    Default: false
    Description: Specifies whether the instances launched in the VPC get DNS hostnames
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Fn::Join:
          - .
          -
            - Ref: VPCSupernetPrefix
            - 0.0/16
      EnableDnsHostnames:
        Ref: EnableDnsHostnames
      Tags:
        - Key: Name
          Value:
            Ref: VPCName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value:
            Ref: VPCName

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway

  RouteTableInternetGateway:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - ""
              -
                - Direct Internet (
                - Ref: VPCName
                - )

  RouteInternetGateway:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: RouteTableInternetGateway
