# RDS DB Subnet groups
---

Resources:

  DBSubnetPrivate:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription:
        Fn::Join:
          - ""
          -
            - Private (
            - Ref: VPCName
            - )
      SubnetIds:
        - Ref: SubnetPrivateAZA
        - Ref: SubnetPrivateAZB
        - Ref: SubnetPrivateAZC

  DBSubnetPublic:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription:
        Fn::Join:
          - ""
          -
            - Public (
            - Ref: VPCName
            - )
      SubnetIds:
        - Ref: SubnetPublicAZA
        - Ref: SubnetPublicAZB
        - Ref: SubnetPublicAZC
